"""Create the initialization tables

Revision ID: b789d290e381
Revises: 
Create Date: 2024-11-22 21:02:10.515316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b789d290e381'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='packing_optimization'
    )
    op.create_index(op.f('ix_packing_optimization_boxes_id'), 'boxes', ['id'], unique=False, schema='packing_optimization')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='packing_optimization'
    )
    op.create_index(op.f('ix_packing_optimization_orders_id'), 'orders', ['id'], unique=False, schema='packing_optimization')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('weight', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='packing_optimization'
    )
    op.create_index(op.f('ix_packing_optimization_products_id'), 'products', ['id'], unique=False, schema='packing_optimization')
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='packing_optimization'
    )
    op.create_index(op.f('ix_packing_optimization_warehouses_id'), 'warehouses', ['id'], unique=False, schema='packing_optimization')
    op.create_table('order_lines',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['packing_optimization.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['packing_optimization.products.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id'),
    schema='packing_optimization'
    )
    op.create_table('product_warehouse_locations',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('x_coordinate', sa.Integer(), nullable=False),
    sa.Column('y_coordinate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['packing_optimization.products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['packing_optimization.warehouses.id'], ),
    sa.PrimaryKeyConstraint('warehouse_id', 'product_id'),
    schema='packing_optimization'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_warehouse_locations', schema='packing_optimization')
    op.drop_table('order_lines', schema='packing_optimization')
    op.drop_index(op.f('ix_packing_optimization_warehouses_id'), table_name='warehouses', schema='packing_optimization')
    op.drop_table('warehouses', schema='packing_optimization')
    op.drop_index(op.f('ix_packing_optimization_products_id'), table_name='products', schema='packing_optimization')
    op.drop_table('products', schema='packing_optimization')
    op.drop_index(op.f('ix_packing_optimization_orders_id'), table_name='orders', schema='packing_optimization')
    op.drop_table('orders', schema='packing_optimization')
    op.drop_index(op.f('ix_packing_optimization_boxes_id'), table_name='boxes', schema='packing_optimization')
    op.drop_table('boxes', schema='packing_optimization')
    # ### end Alembic commands ###
